---
- name: Prepare
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  roles:
    - prepare

- name: Install node
  hosts: '{{ target }}'
  gather_facts: false
  roles:
    - standard_node_installation
    - initialize_archway
#    - launch_node
