---
- name: install apt packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - make
    - build-essential
    - gcc
    - git
    - jq
    - chrony

- name: Download go
  get_url:
    url: 'https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz'
    dest: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    mode: '0700'

- name: unarchive go
  unarchive:
    src: '/tmp/go{{ go_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/usr/local/'
    owner: root
    group: root
    mode: '0755'

- name: Go get cosmovisor
  command: 'go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@v{{ cosmovisor_version }}'
  environment:
    PATH: '{{ path }}'
    GOPATH: '/home/{{ ansible_user }}/go'

- name: Change go folder permission
  file:
    path: /home/{{ ansible_user }}/go
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: true
    mode: '0755'

- name: copy .profile
  template:
    src: 'profile.j2'
    dest: '/home/{{ ansible_user }}/.profile'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0600'

- name: copy cosmovisor service file
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/cosmovisor.service'
    owner: root
    group: root
    mode: '0600'
